### ISSUE TITLE
Defect ID_WM01

### ISSUE THREAD

**Issue by gurleensingh** [gurleensingh/IT7351WardrobeManager#1]
Incomplete Season List in the drop down:

When adding an item to an inventory and filling item details, the season drop down list only displays two season i.e. Summer and Winter.

Spring and Autumn season needs to be added.

**Comment by gurleensingh** [comment]
Defect Moved to Sprint 2 development for a fix. @amanchhabra001 - please fix this defect in next sprint dev

**Comment by gurleensingh** [comment]
Defect Update: Cosmetic Defect -
Currently Season list displays 4 seasons - Winter, Summer, Rainy and Spring

Rainy season should be replace by Autumn season

**Comment by amanchhabra001** [comment]
Hi Gurleen,
I solved sprint 1 defect.
That is my mistake, i will change the name rainy to Autumn season.

**Comment by gurleensingh** [comment]
Season drop down list is fine now

Test Ok.

Closing the defect.

**Comment by shubh407** [comment]
Good Work! finally defect is close.

**Comment by amanchhabra001** [comment]
:)
