### ISSUE TITLE
DefectID_WM02

### ISSUE THREAD

**Issue by gurleensingh** [gurleensingh/IT7351WardrobeManager#2]
Item ID not generated and Item details not displayed on adding an Item:

When a new Item is added to the inventory, a unique Item ID is not generated and Item details are not displayed in a POP up.

**Comment by gurleensingh** [comment]
This defect is also moved to Sprint 2 development.

Shubham please assist Aman in this.

**Comment by shubh407** [comment]
Hi Gurleen!

Yes i will look into this today and assist Aman.

On Sun, Sep 13, 2015 at 9:24 PM, gurleensingh notifications@github.com
wrote:

> This defect is also moved to Sprint 2 development.
> 
> Shubham please assist Aman in this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gurleensingh/IT7351WardrobeManager/issues/2#issuecomment-139855719
> .

## 

Kind Regards
Shubham

**Comment by amanchhabra001** [comment]
Hi Gurleen,
I am working on that and will let u conform when i did that. :)

**Comment by amanchhabra001** [comment]
Hi Gurleen,
I have completed packing requirement's layouts and coding.

**Comment by amanchhabra001** [comment]
Gurleen, 
I again tried but i got problem to "push and commit" coding and layouts to Github.

**Comment by gurleensingh** [comment]
Unique Item ID is generated for each new item added and POP displaying the unique ID is displayed.

Defect tested.

Closing the defect.

**Comment by shubh407** [comment]
ok!
