### ISSUE TITLE
Sprint 3 Backlog

### ISSUE THREAD

**Issue by gurleensingh** [gurleensingh/IT7351WardrobeManager#3]
Story 9 : Non Functional Requirement: To create calendar view
Story 10: Functional Requirement: To create the functionality to track an outfit on daily basis
Story 11: Functional Requirement: To incorporate the functionality to pre plan outfit for future events
                                                        based on the input criteria

**Comment by gurleensingh** [comment]
Input Criteria for Pre Planning out fit is:
1.Colour of the Item
2. Dress Code

Refer to Sprint 3 backlog document (Product and Sprint Backlog_Wardrobe Manager.xlsx)

[Product and Sprint Backlog_Wardrobe Manager.xlsx](https://github.com/gurleensingh/IT7351WardrobeManager/files/2834/Product.and.Sprint.Backlog_Wardrobe.Manager.xlsx)

**Comment by gurleensingh** [comment]
Missing Functionality from Sprint 2 are adding in Sprint 3 - Refer to Sprint 2 Updates Issue on GIT Hub

**Comment by shubh407** [comment]
I and Aman are working on the sprint 3.

**Comment by amanchhabra001** [comment]
Gurleen, 
We will be update the status after sort out this.

**Comment by gurleensingh** [comment]
Input Criteria for Create packing is working fine now

**Comment by gurleensingh** [comment]
Aman is still working on the Track Outfit and Pre Plan Outfit functionality. So these are moved to Sprint 4.
Closing Sprint 3 here.

**Comment by shubh407** [comment]
ok!
