### ISSUE TITLE
Sprint 2 Updates

### ISSUE THREAD

**Issue by gurleensingh** [gurleensingh/IT7351WardrobeManager#4]
Sprint 2 Completed on 25 September 2015, 4 days late from the schedules time.

Two functionalities are missing from Sprint 2: (Sprint 2 Defects)
1. No Input Criteria for Create Packing
2. No option for the User to download the Packing list

The development of these functionalities are moved to Sprint 3

**Comment by amanchhabra001** [comment]
Gurleen, i will solve this problem as soon as possible and will update the information.
Thanks

**Comment by gurleensingh** [comment]
I have committed the Sprint 2 deliverable codes

**Comment by gurleensingh** [comment]
Closing Sprint 2
