### ISSUE TITLE
Sprint 4 Backlog

### ISSUE THREAD

**Issue by gurleensingh** [gurleensingh/IT7351WardrobeManager#6]
Team need to develop the following functionalities in Sprint 4:

Create Style Expert View
Display Blogs and Trends
Display Colour Chart
Display Size Chart
Create Track Outfit and Pre Plan outfit functionality

**Comment by shubh407** [comment]
Yes we are on sprint 4 and i am working with Aman on Style Expert

**Comment by amanchhabra001** [comment]
Yes Gurleen, we are working on this. Let you know about update.
